spring:
  jpa:
    # Hay que revisar esta condicion
    open-in-view: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev
    username: dev
    password: 123456


---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:C:/temp/test
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev
    username: dev
    password: 123456

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tools
    username: postgres
    password: 123456

